name: CI/CD

on:
  push:
    branches:
      - "*/**"
      - "*"
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: ./ci/build.ps1
        shell: pwsh
      - name: Publish
        run: ./ci/publish.ps1
        shell: pwsh